PopPool/iOS

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Application/AppDelegate.swift
PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPoolTests/Application/AppDIContainerTest.swift

- AppDIContainer 구현
- AppDIContainer 테스트 작성
- PopPool/Application 디렉토리에 DIContainer 추가
- PopPoolTests 디렉토리에 Application 추가하여 테스트 케이스 구성
- register<T>(type: T.Type, component: AnyObject): 특정 타입에 대한 컴포넌트를 등록합니다.
- resolve<T>(type: T.Type) -> T : 특정 타입에 대한 컴포넌트를 반환합니다.
```
AppDIContainer.shared.register(type: Animal.self, component: Dog(name: "백구")) // 등록
let dog = AppDIContainer.shared.resolve(type: Animal.self) // 반환
```
- ✅ func testAppDIContainer() : Dog 인스턴스 등록 후 반환 값 확인
- ✅ func testChangeAppDIConainer(): Dog 인스턴스 등록 후 Cat 인스턴스로 변경 후 반환 값 확인

[MERGE] DIContainer

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/xcshareddata/xcschemes/PopPool.xcscheme
PopPool/PopPool/Application/AppDelegate.swift
PopPool/PopPool/Data/Network/APIEndpoint.swift
PopPool/PopPool/Data/Network/Common/NetworkError.swift
PopPool/PopPool/Data/Network/DTO/Request/TestRequestDTO.swift
PopPool/PopPool/Data/Network/DTO/Response/TestResponseDTO.swift
PopPool/PopPool/Data/Network/EndPoint/EndPoint.swift
PopPool/PopPool/Data/Network/EndPoint/Requestable.swift
PopPool/PopPool/Data/Network/EndPoint/Responsable.swift
PopPool/PopPool/Data/Network/MockTest/MockUrlSession.swift
PopPool/PopPool/Data/Network/Provider/Provider.swift
PopPool/PopPool/Data/Network/Provider/URLSessionable.swift
PopPool/PopPool/Data/Network/Response.swift
PopPool/PopPool/Presentation/CodeConvention Sample/ViewController.swift
PopPool/PopPoolTests/PopPoolTests.swift

- 네트워크 기본 통신 데이터 구성
- Clean Architecture 방식에 맞춰 구조 구성 시도
- 네트워크 테스트 작성 -> 일단 제외
- PopPool/Network 디렉토리에 Network 컴포넌트별 추가
e.g) Common, DTO, Endpoint, MockTest, Provider
- PopPoolTests 디렉토리에 testFetchJoke 테스트 메서드 추가
- 테스트 케이스는 추후 업데이트하기로 진행

Network Layer 추가 정리

---

PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPoolTests/Application/AppDIContainerTest.swift

- DIContainer 에 identifier 기능을 추가하였습니다.
- 기존 메서드 사용시 default라는 문자열으로 identifier가 설정 됩니다.
```
/// 식별자로 강아지, 고양이 등록후 반환 값 확인 -> Test ✅
func testIdentifier() {
AppDIContainer.shared.register(type: Animal.self, identifier: "강아지", component: Dog(name: "백구"))
AppDIContainer.shared.register(type: Animal.self, identifier: "고양이", component: Cat(name: "나비"))
let dog = AppDIContainer.shared.resolve(type: Animal.self, identifier: "강아지")
let cat = AppDIContainer.shared.resolve(type: Animal.self, identifier: "고양이")
XCTAssertTrue(cat.name == "나비" && dog.name == "백구")
}
```

[MERGE]: ✅ Refactor/di container

---

PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPool/Domain/Interfaces/AuthService.swift
PopPool/PopPool/Domain/Interfaces/FetchUserCredentialUseCase.swift
PopPool/PopPool/Domain/UseCase/FetchUserCredentialUseCaseImpl.swift
PopPool/PopPool/Infrastructure/Service/AuthService/Services/AppleAuthServiceImpl.swift
PopPool/PopPool/Infrastructure/Service/AuthService/Services/KakaoAuthServiceImpl.swift

- FetchUserCredentialUseCase를 수정하였습니다.
- 추후 PopPoolAPIEndpoint 수정 예정입니다.
- 추후 KakaoLoginRequestDTO 삭제 예정입니다.
- 식별자를 통해 UseCase 2가지를 등록하였습니다.
- 기존 Response 타입을 직접 명시하는 코드에서 Encodable을 리턴하는 것으로 EndPoint의 BodyParam에 사용하기 쉽도록 통일하였습니다.
```
var kakaoUseCase: FetchUserCredentialUseCase
var appleUseCase: FetchUserCredentialUseCase
init() {
self.kakaoUseCase = AppDIContainer.shared.resolve(type: FetchUserCredentialUseCase.self, identifier: "Kakao")
self.appleUseCase = AppDIContainer.shared.resolve(type: FetchUserCredentialUseCase.self, identifier: "Apple")
}
func exampleKakao() {
kakaoUseCase.execute()
.subscribe { userCredential in
print(userCredential)
} onError: { error in
print(error)
}
.disposed(by: disposeBag)
}
```

[MERGE] : ✅ FetchUserCredentialUseCase

---

PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Presentation/Common/Extension/UIColor+.swift
PopPool/PopPool/Resource/Info.plist

- 폰트가 적용되지 않는 문제점을 해결했습니다.
- UIColor 중 blu가 보이지 않는 문제점을 해결했습니다.
- 폰트의 확장자가 빠져있어 폰트가 적용되지 않고 있었습니다.
폰트별 확장자 추가 정리하여 올려두었습니다.
- 피그마에서 blue의 hex 값이 잘못 적용되어 있었습니다.
올바른 값을 찾아 변경하였습니다.

[HOTFIX]: 💥 UIFont, UIColor 이슈 해결

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Presentation/Common/Extension/UIFont.swift

논의한대로 국문 영문 코드 스타일을 변경하였습니다
- 폰트를 조금 더 편하게 생성할 수 있습니다
- KorFont와 EngFont로 나뉩니다
**기존 코드**
```
enum KorFont {
case regular(size: Size)
case light(size: Size)
case medium(size: Size)
case bold(size: Size)
var name: UIFont! {
switch self {
case .bold(let size): return UIFont(name: "GothicA1-Bold", size: size.rawValue)
case .light(let size): return UIFont(name: "GothicA1-Light", size: size.rawValue)
case .medium(let size): return UIFont(name: "GothicA1-Medium", size: size.rawValue)
case .regular(let size): return UIFont(name: "GothicA1-Regular", size: size.rawValue)
}
}
}
testlabel.text.font = .KorFont.bold(size: ._12).name
```
**변경 코드**
```
static func KorFont(style: FontStyle, size: CGFloat) -> UIFont? {
return UIFont(name: "GothicA1\(style.rawValue)", size: size)
}
testLabel.text.font = …
```

[HOTFIX]: 💥 영문, 국문 Font 코드 수정

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPool/Infrastructure/Service/AuthService/Services/AppleAuthServiceImpl.swift
PopPool/PopPool/Presentation/CodeConvention Sample/ViewControllerViewModel.swift
PopPool/PopPool/Presentation/Common/Enums/DatabaseTYPE.swift
PopPool/PopPool/Presentation/Common/Enums/SocialTYPE.swift
PopPool/PopPool/Presentation/Common/Extension/UIFont+.swift
PopPool/PopPool/Presentation/Common/Interfaces/Inputable.swift
PopPool/PopPool/Presentation/Common/Interfaces/Outputable.swift
PopPool/PopPool/Presentation/Common/Interfaces/ViewModelable.swift
PopPool/PopPool/Presentation/Common/Manager/ToastMSGManager.swift
PopPool/PopPool/Presentation/Common/Utility/Constants.swift
PopPool/PopPool/Presentation/Components/ButtonCPNT.swift
PopPool/PopPool/Presentation/Components/ContentTitleCPNT.swift
PopPool/PopPool/Presentation/Components/ProgressIndicatorCPNT.swift
PopPool/PopPool/Presentation/Components/ProgressViewCPNT.swift
PopPool/PopPool/Presentation/Components/ToastMSGCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Components/CheckBoxCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Components/TermsViewCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/VCSignUp.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/VMSignUp.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep1View.swift

- 오해의 소지가 발생할 수 있어 타입명칭을 변경
- 타입이외에 Interface, Components, Enum, Constants 등 또한 수정 완료
- 기존 합의한 CMPTToastMSG, TYPEButton 같은 타입 명칭에서 ToastMSGCPNT, ButtonTYPE으로 수정 진행
*ViewController, ViewModel 등 scene에 필요한 파일 생성이 되며 네이밍으로 인한 오해 증가, 가독성을 헤치는 이슈로 함께 리팩토링 진행*

[MERGE]: ✅ Code Naming Convention 일괄 수정

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Application/SceneDelegate.swift
PopPool/PopPool/Presentation/Common/Extension/UICollectionViewCell+.swift
PopPool/PopPool/Presentation/Common/Extension/UITableViewCell+.swift
PopPool/PopPool/Presentation/Common/Layout/TagsLayout.swift
PopPool/PopPool/Presentation/Components/SegmentedControlCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Components/CheckBoxCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVM.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/LargeChipCell.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep1View.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep3View.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep4View.swift

- Sign Up Step 3 View, SegmentedControlCPNT 개발 완료하여 확인 부탁드립니다.
- 관심사 목록은 하드코딩으로 주입한 상태이며 추후 네트워크를 통해 주입할 수 있도록 수정 하겠습니다.
- 유저명 부분 색인 효과도 Step 2 View 개발 완료 후 수정하겠습니다.
- LargeChipCell 추가
- TagLayout 추가
- SignUpStep3View 추가
- SegmentedControlCPNT 추가
https://github.com/PopPool/iOS/assets/112812473/5414b17f-7139-425c-acf0-f8592a482274
https://github.com/PopPool/iOS/assets/112812473/2cc289e5-6165-4760-a72a-a53aaa8a6cc9
https://github.com/PopPool/iOS/assets/112812473/52ccc0fa-a949-402f-87e0-e4e3f96d73ac
https://github.com/PopPool/iOS/assets/112812473/276ebd2c-dfdb-4cad-887f-13f566da1514
```
private let segmentedControl: SegmentedControlCPNT = SegmentedControlCPNT(
type: .base,
segments: ["남성", "여성", "선택안함"],
selectedSegmentIndex: 2
)
private let segmentedControl: SegmentedControlCPNT = …
```

[MERGE] : ✅ SignUp Step 3 View, SegmentedControlCPNT

---

PopPool/PopPool/Presentation/Components/HeaderViewCPNT.swift

- HeaderView Fix
```
private let headerView: HeaderViewCPNT = {
let view =  HeaderViewCPNT(title: "하하호호", style: .text("취소"))
return view
}()
```
```
private let headerView: HeaderViewCPNT = {
let iconImage = UIImage(named: "icosolid")
let view =  HeaderViewCPNT(title: "하하호호", style: .icon(iconImage))
return view
}()
```
```
private let headerView: HeaderViewCPNT = {
let iconImage = UIImage(named: "icosolid")
let view =  HeaderViewCPNT(title: "하하호호", style: .icon(iconImage))
view.titleLabel.isHidden = true
return view
}()
```
```
private let headerView: HeaderViewCPNT = {
let iconImage = UIImage(named: "icosolid")
let view =  HeaderViewCPNT(title: "하하호호", style: .icon(iconImage))
view.titleLabel.isHidden = true
view.leftBarButton.isHidden = true
return view
}()
```

[MERGE] : ✅ HeaderView Fix

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Presentation/Common/Extension/UIView+.swift
PopPool/PopPool/Presentation/Common/Utility/Factory.swift
PopPool/PopPool/Presentation/Components/CMPTInfoBoxView.swift
PopPool/PopPool/Presentation/Components/CMPTToolTipView.swift
PopPool/PopPool/Presentation/Components/ToastMSGCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginBottomSheet/LoginBottomSheetVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVM.swift

- 이제 ToolTip의 컬러와 섀도우가 변경됩니다!
- ToolTip의 제약을 새로 잡았습니다
- ToolTip에 섀도우를 추가했습니다
- 컬러별로 텍스트 색상이 바뀌도록 수정되었습니다 (색상은 2가지로 고정해두었습니다)
한번에 툴팁의 모습을 그리지 않고 팁과 메시지 영역을 따로 구분하여 생성할 수 있도록 만들어 두었습니다.
UIBezierPath를 생성할 때 프레임을 활용하여 그려야하는 이슈로 원하는 방향의 툴팁을 생성하기 위해서 프레임으로 진행하였습니다..!
<br/>
- 로그인 페이지에서는 2개의 팁이 생성되어 있습니다!
- setToolTip 메서드에서 어떤 플랫폼 서비스가 눌렸는지에 따라 적용될 수 있도록 if 문 안에 들어가 있는 상황입니다..!
```
// 컴포넌트
lazy var belowTip = CMPTToolTipView(colorType: .blu500, direction: .pointDown)
lazy var aboveTip = CMPTToolTipView(colorType: .blu500, direction: .pointUp)
// 메서드
private func setToolTip() {
if false {
view.addSubview(belowTip)
belowTip.snp.makeConstraints { make in
make.bottom.equalTo(kakaoSignInButton.snp.top).inset(-8)
make.centerX.equalToSuperview()
}
} else {
view.addSubview(aboveTip) …
```

[MERGE]: ✅ 툴팁 섀도우 및 컬러별 수정 적용

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpCompletedVC.swift

- 이제 어플에서 signUp 완료 페이지가 보일 수 있습니다.
*화면 연결은 필요한 상황입니다.
- 유저 닉네임과 카테고리 태그를 인자로 받을 수 있습니다.
- Figma에 맞춰 signup complete 화면이 구현됐습니다.
initializer에서 nickname과 tag 값을 받습니다.
아래 예시와 init 코드는 참고 부탁 드립니다!
```
init(nickname: String?, tags: [String]?) {
self.userName = nickname
self.categoryTags = tags
super.init(nibName: nil, bundle: nil)
setUpConstraints()
setNickName()
setCategory()
}
// MARK: - 활용 예시
let interests = ["패션", "게임",  "iOS", "개발" ]
let vc = SignUpCompletedVC(nickname: 서준여이, tags: interests)
```

[MERGE] : ✅ SignUp Completed View

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Data/Network/PopPoolNetwork/Interceptor/TokenInterceptor.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/LoginDTO/LoginResponseDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
PopPool/PopPool/Data/Repositories/SignUpRepository/SignUpRepositoryImpl.swift
PopPool/PopPool/Data/Repositories/SignUpRepository/SignUpRepositoryTest.swift
PopPool/PopPool/Domain/Entities/LoginResponse.swift
PopPool/PopPool/Domain/Interfaces/SignUpRepository.swift
PopPool/PopPool/Infrastructure/Network/Provider/Provider.swift
PopPool/PopPoolTests/Domain/UseCase/FetchSocialUserCredentialUseCaseTest.swift

- Token Interceptor 적용
- 엔티티 수정
- provider 수정
- DTO수정
- kakao Test Code 작성 실패..

[MERGE]: ✅ Token Interceptor 적용 및 엔티티 수정

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Presentation/Components/BaseTextFieldCPNT.swift
PopPool/PopPool/Presentation/Components/ValidationTextFieldCPNT.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVM.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep2View.swift

- 이전 브랜치는 project 이슈가 발생하여 새로운 브랜치에 validationTF 관련 코드를 올립니다.
- 텍스트 필드 입력 데이터에 따라 컬러가 올바르게 바뀝니다.
- 타입 중인 상황에서 clearbutton이 보입니다
- 타입을 멈추고 키보드를 내렸을 때 중복 체크 버튼이 활성화 됩니다
**- screen2의 코드들은 모두 연결 해제해둔 상태입니다**
https://github.com/PopPool/iOS/assets/119504454/ba770ad0-e920-4ca6-a220-4d4a05d79657

[MERGE]: ValidationTF status별 반응 코드 추가

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Presentation/Common/Cells/TableViewSection/MenuListCellSection.swift
PopPool/PopPool/Presentation/Common/Cells/TableViewSection/MyCommentCircleListCellSection.swift
PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/CircleFeedCell.swift
PopPool/PopPool/Presentation/Common/Cells/UITableViewCell/MenuListCell.swift
PopPool/PopPool/Presentation/Common/Cells/UITableViewCell/MyCommentCircleListCell.swift
PopPool/PopPool/Presentation/Common/Interfaces/TableViewSectionable.swift
PopPool/PopPool/Presentation/Scene/MyPage/MyPageMainVM.swift

- 내 코멘트 Cell 개발,
- TableViewSectionable Cell Output 헨들링 추가
- CellSection 파일들 분리
```
// MARK: - transform
func transform(input: Input) -> Output {
// section Output 처리
myCommentSection.sectionOutput().didTapRightButton
.subscribe { _ in
print("MyComment section Button Tapped")
}
.disposed(by: disposeBag)
// Cell Output 처리
// Cell의 Output과 indexPath를 함께 전달합니다.
myCommentSection.sectionCellOutput.subscribe { (output, indexPath) in
output.didSelectCell.subscribe { cellIndexPath in
print(indexPath,cellIndexPath)
}
.disposed(by: self.disposeBag)
}
.disposed(by: disposeBag)
return Output()
}
```
- MyPage 작업 상황

[MERGE] : ✅ 내 코멘트 Cell 개발, TableViewSectionable Cell Output 헨들링 추가, 등

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/SignUpDTO/SignUpRequestDTO.swift
PopPool/PopPool/Data/Repositories/SignUpRepository/SignUpRepositoryImpl.swift
PopPool/PopPool/Data/Repositories/SignUpRepository/SignUpRepositoryTest.swift
PopPool/PopPool/Domain/Interfaces/AuthService.swift
PopPool/PopPool/Domain/Interfaces/FetchSocialCredentialUseCase.swift
PopPool/PopPool/Domain/Interfaces/SignUpRepository.swift
PopPool/PopPool/Domain/Interfaces/SignUpUseCase.swift
PopPool/PopPool/Domain/UseCase/FetchSocialCredentialUseCaseImpl.swift
PopPool/PopPool/Domain/UseCase/SignUpUseCaseImpl.swift
PopPool/PopPool/Infrastructure/Network/Common/NetworkError.swift
PopPool/PopPool/Infrastructure/Network/EndPoint/RequestEndPoint.swift
PopPool/PopPool/Infrastructure/Network/Interceptor/RequestTokenInterceptor.swift
PopPool/PopPool/Infrastructure/Network/Provider/Provider.swift
PopPool/PopPool/Infrastructure/Service/AuthService/Services/AppleAuthServiceImpl.swift
PopPool/PopPool/Infrastructure/Service/AuthService/Services/KakaoAuthServiceImpl.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVM.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVM.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep3View.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep4View.swift
PopPool/PopPool/Resource/Info.plist

- Provider에 Request 전용 메서드를 생성하였습니다
- Request EndPoint를 이용하여 응답이 없는 요청을 생성합니다.
- RequestTokenInterceptor를 이용하여 retry를 하지 않는 요청을 보냅니다.
- SignUp 프로세스의 건너뛰기를 제외한 기능을 연결하였습니다.
- 개발시 테스트를 위해 임시로 HTTP URL 요청 허용을 처리하였습니다.
- AuthService에서 Response 만 Encodable로 사용한 기존의 방식에서 Response의 제네릭 명을 Credential로 변경후 AuthSeriveResponse 타입에 종속시켜 사용합니다. 변경의 이유는 회원가입시 필요한 SocialType, UserEmail등을 포함한 리턴값을 사용하기 위하여 변경하였습니다.
- 특이사항: Apple 소셜로그인의 경우 단 한번의 초기 로그인에서만 유저에게 Email을 요청할 수 있습니다.
- 기존의 Interests관련 API는 문자열을 요청에 싣어 보내는 형식에서 스웨거 및 백엔드 개발자 분과 이야기하여 관심사의 키값에 해당하는 정수를 싣는 형태로 변경하였습니다.

[MERGE]: ✅ SignUp API Connect

---

PopPool/PopPool.xcodeproj/project.pbxproj

- HomeDTO 병합 이후 project 파일에서 누락된  '};'로 빌드가 되지 않던 이슈 해결

[HOTFIX]: 💥🚚 병합 후 프로젝트 파일 충돌 이슈 해결

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/NoticeDTO/GetNoticeDetailResponseDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/NoticeDTO/GetNoticeListResponseDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/NoticeDTO/NoticeInfoDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
PopPool/PopPool/Data/Repositories/NoticeRepository/NoticeRepositoryImpl.swift
PopPool/PopPool/Domain/Entities/NetworkResponse/Notice/GetNoticeDetailResponse.swift
PopPool/PopPool/Domain/Entities/NetworkResponse/Notice/GetNoticeListResponse.swift
PopPool/PopPool/Domain/Entities/NetworkResponse/Notice/NoticeInfo.swift
PopPool/PopPool/Domain/Interfaces/NoticeRepository.swift
PopPool/PopPool/Domain/Interfaces/NoticeUseCase.swift
PopPool/PopPool/Domain/UseCase/NoticeUseCaseImpl.swift
PopPool/PopPool/Presentation/Common/Extension/Date+.swift
PopPool/PopPool/Presentation/Common/Extension/String+.swift
PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
PopPool/PopPool/Presentation/Scene/MyPage/Notice/Cells/NoticeTableViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Notice/Detail/NoticeDetailBoardVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Notice/Detail/NoticeDetailBoardVM.swift
PopPool/PopPool/Presentation/Scene/MyPage/Notice/Main/NoticeBoardVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Notice/Main/NoticeBoardVM.swift
PopPool/PopPool/Presentation/Scene/MyPage/TermBoard/TermsBoardVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift

- 공지사항 기능연결
- Date -> String extension 추가
- String -> Date extension 추가 [현 서버에서 내려주는 포멧을 Date타입으로 변환]
- Notice Repository 추가
- Notice UseCase 추가
https://github.com/user-attachments/assets/e6f01b72-0a02-41ba-87c2-86162d0c1077

[MERGE] : Notice 기능 연결

---

PopPool/PopPool/Presentation/Common/Extension/String+.swift
PopPool/PopPool/Presentation/Scene/MyPage/MyCommentedPopUp/MyCommentedPopUpVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/MyCommentedPopUp/MyCommentedPopUpVM.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift

- MyCommented Popup Pagination
https://github.com/user-attachments/assets/df475b2d-0014-476a-880a-6c769c3e3762

[MERGE]: MyCommented Popup Pagination

---

PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/SurveyDTO/CheckedSurveyListRequestDTO.swift
PopPool/PopPool/Data/Repositories/UserRepository/UserRepositoryImpl.swift
PopPool/PopPool/Domain/Interfaces/UserRepository.swift
PopPool/PopPool/Domain/Interfaces/UserUseCase.swift
PopPool/PopPool/Domain/UseCase/UserUseCaseImpl.swift
PopPool/PopPool/Presentation/Scene/MyPage/SignOut/SignOutCompleteVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/SignOut/SignOutCompleteVM.swift

[MERGE]: 회원탈퇴 mapping 이슈 해결

---

PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/SectionHeaderCell.swift

- 섹션별 헤더 탭 시 알맞는 페이지로 이동이 가능합니다.
- 탭바 적용 이후 섹션별 헤더 탭이 안되는 이슈를 해결했습니다.
- 섹션별 switch문의 분기를 제대로 타고 있지 않아 dataSource 내부에서 활용하던 self = navigationController.topViewController를 제거하였습니다
- 셀이 재사용되면서 데이터를 반복적으로 호출하는 이슈 발견, reuseCell 메서드를 추가 적용
- dispose가 제대로 되지 않고 있던 이슈 발견, 셀의 disposebag로 이벤트 처리 권한을 넘김

MERGE: ✅ 탭바 적용 이후 섹션별 헤더 탭 안되는 이슈 해결

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool/Application/DIContainer/AppDIContainer.swift
PopPool/PopPool/Data/Network/PopPoolAPIEndPoint.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/ActionType.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/ImageActionDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/PostCommentRequestDTO.swift
PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/UpdateCommentRequestDTO.swift
PopPool/PopPool/Data/Repositories/CommentRepository/CommentRepositoryImpl.swift
PopPool/PopPool/Data/Repositories/HomeRepository/HomeRepositoryImpl.swift
PopPool/PopPool/Domain/Interfaces/CommentRepository.swift
PopPool/PopPool/Domain/Interfaces/CommentUseCase.swift
PopPool/PopPool/Domain/UseCase/CommentUseCaseImpl.swift
PopPool/PopPool/Presentation/Components/ListTitleViewCPNT.swift
PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/CommentTypeVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/NormalCommentVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/NormalCommentVM.swift

- 코멘트 작성을 할 수 있습니다
*단, 현재 백엔드 쪽에서 오류가 있어 서버 오류가 발생하고 있는 상황입니다.
- 코멘트 업로드에 필요한 DTO 및 데이터 모델 또한 추가 되었습니다.
- 기존 HomeRepositoryImpl에 있던 TokenInterceptor를 제거하였습니다.
* 서버에서 데이터를 호출 받는 입장에서 별도로 토큰을 보내야할 이유가 없어 제거하였습니다.
** 스웨거에서 데이터 오류가 발생하는 이슈는 해결한 이후 확인하여 팔로업 내용 남기도록 하겠습니다~

[MERGE]: ✅ Linked Comment Server Upload feature

---

PopPool/PopPool/Domain/Entities/HomePopUp.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeDetailPopUpCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/InterestViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/SectionHeaderCell.swift

[MERGE]: ✅ section Title attribute 수정

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Presentation/Common/Extension/UIImageView+.swift
PopPool/PopPool/Presentation/Common/View/CoverView.swift

- setClosedNotice 메서드를 생성했습니다.
*날짜 데이터를 넘길 수 있도록 정리했습니다. 종료 일정인 string 데이터를 전달하면 됩니다.
- 원하는 위치에서 메서드를 호출하면 coverView를 더할 수 있습니다

[MERGE]: ✅ ImageCoverView added

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Data/Network/PopPoolNetwork/AdminDTO/AdminPopUpStoreDTO.swift
PopPool/PopPool/Presentation/Common/Extension/UIImageView+.swift
PopPool/PopPool/Presentation/Components/LoadingIndicator.swift
PopPool/PopPool/Presentation/Scene/Admin/Edit/AdminEditVC.swift
PopPool/PopPool/Presentation/Scene/Admin/Management/AdminManagementListTableViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeDetailPopUpCell.swift

- presignedUrl로 이미지 다운로드 시, indicator를 적요할 수 있는 UIImageView extension을 생성했습니다.
- setPresignedImage(from string: [String], service: PreSignedService, bag: DisposeBag)를 호출하여 적용해주세요.
*UIImageView를 확장하였기에 disposeBag를 넘겨주는 형태로 구성해보았습니다.
```swift
e.g)
func injectionWith(input: Input) {
if let path = input.image {
let service = PresignedService()
let disposeBag = DisposeBag()
testImageView.setPresignedImage(from: path, service: service, bag: disposeBag)
}
```
- 데이터 호출이 올바르게 되지 않아 bannerYn을 임시로 제거하였습니다.
https://github.com/user-attachments/assets/f12b9e6e-c68e-48b9-aea0-b20492328db3

[MERGE]: ✅ loadingIndicator 적용

---

PopPool/PopPool.xcodeproj/project.pbxproj
PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PopPool/PopPool/Data/Network/PopPoolAPIEndPoint.swift
PopPool/PopPool/Infrastructure/Service/URLSchemeService.swift
PopPool/PopPool/Presentation/Scene/Map/URLSchemeService.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/Search/SearchViewController.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/FindRouteViewController.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/GetPopUpStoreDirectionResponseDTO.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/PopUpDetailUseCase.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/PopUpDetailViewController.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/PopupDetailViewModel.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/PopupRepository.swift
PopPool/PopPool/Presentation/Scene/PopUpDetail/SimilarPopupCell.swift

찾아가는길에서 버튼을 탭했을때 외부 . 앱및 앱스토어 연결을위한 (  URLSchemeService.swift
) 파일이 추가되었습니다 . 
찾아가는길 모달뷰에서의 UI가 일부 수정되었습니다. 
Direction EndPoint 가 추가되었습니다

[MERGE] :  찾아가는길 외부 앱스토어 연결을위한 URL 스킴 추가.및 , 찾아가는길 모달뷰 UI 일부 수정

---

PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/InstagramCommentView/SocialCommentVC.swift

- header가 바인딩 되지 않아 리턴이 되지 않는 이슈 해결
- social Comment와 normal Comment에서 사용되는 header의 위치가 미묘하게 달랐는데요.
스택 뷰에 들어가면서 발생하는 문제였습니다. UI 또한 수정하였습니다.

[MERGE]: ✅ social Comment 리턴이 되지 않는 이슈 해결

---

PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/CircleFeedCell.swift
PopPool/PopPool/Presentation/Common/Extension/UIImageView+.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeCollectionViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeDetailPopUpCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/PopularViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Main/Views/MyPageMainProfileView.swift

- 데이터를 모두 받은 이후 이미지와 텍스트 등이 동일하게 보일 수 있도록 수정하였습니다.
- 이미지를 받아오는 시점에 인디케이터만 보여야하는 단계에서 이미지는 비어있는 반면, 텍스트는 모두 보이는 이슈가 있어 수정하였습니다
- 추가로  Rx 형식으로 변경 적용해보았습니다.

[MERGE]: ✅ Image Indicator 로드 시점 수정

---

PopPool/PopPool/Domain/Entities/HomePopUp.swift
PopPool/PopPool/Presentation/Common/Extension/UIImageView+.swift
PopPool/PopPool/Presentation/Components/SearchViewCPNT.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/EntirePopupVC.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeCollectionViewCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeDetailPopUpCell.swift
PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeVC.swift
PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift

- Dev 브랜치에 문제를 방지하고자 안전 차원에서 Dev를 복사한 또 다른 브랜치를 생성하였습니다.

[TEST]: 📝 QA 테스트용 머지
