PopPool/iOS

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool.xcodeproj/xcshareddata/xcschemes/PopPool.xcscheme
- PopPool/PopPool/Application/AppDelegate.swift
- PopPool/PopPool/Data/Network/APIEndpoint.swift
- PopPool/PopPool/Data/Network/Common/NetworkError.swift
- PopPool/PopPool/Data/Network/DTO/Request/TestRequestDTO.swift
- PopPool/PopPool/Data/Network/DTO/Response/TestResponseDTO.swift
- PopPool/PopPool/Data/Network/EndPoint/EndPoint.swift
- PopPool/PopPool/Data/Network/EndPoint/Requestable.swift
- PopPool/PopPool/Data/Network/EndPoint/Responsable.swift
- PopPool/PopPool/Data/Network/MockTest/MockUrlSession.swift
- PopPool/PopPool/Data/Network/Provider/Provider.swift
- PopPool/PopPool/Data/Network/Provider/URLSessionable.swift
- PopPool/PopPool/Data/Network/Response.swift
- PopPool/PopPool/Presentation/CodeConvention Sample/ViewController.swift
- PopPool/PopPoolTests/PopPoolTests.swift
- 네트워크 기본 통신 데이터 구성
- Clean Architecture 방식에 맞춰 구조 구성 시도
- 네트워크 테스트 작성 -> 일단 제외
- PopPool/Network 디렉토리에 Network 컴포넌트별 추가
e.g) Common, DTO, Endpoint, MockTest, Provider
- PopPoolTests 디렉토리에 testFetchJoke 테스트 메서드 추가
- 테스트 케이스는 추후 업데이트하기로 진행
> NetworkLayer 구성

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool.xcodeproj/xcshareddata/xcschemes/PopPool.xcscheme
- PopPool/PopPool/Application/AppDelegate.swift
- PopPool/PopPool/Data/Network/APIEndpoint.swift
- PopPool/PopPool/Data/Network/Common/NetworkError.swift
- PopPool/PopPool/Data/Network/DTO/Request/TestRequestDTO.swift
- PopPool/PopPool/Data/Network/DTO/Response/TestResponseDTO.swift
- PopPool/PopPool/Data/Network/EndPoint/EndPoint.swift
- PopPool/PopPool/Data/Network/EndPoint/Requestable.swift
- PopPool/PopPool/Data/Network/EndPoint/Responsable.swift
- PopPool/PopPool/Data/Network/MockTest/MockUrlSession.swift
- PopPool/PopPool/Data/Network/Provider/Provider.swift
- PopPool/PopPool/Data/Network/Provider/URLSessionable.swift
- PopPool/PopPool/Data/Network/Response.swift
- PopPool/PopPool/Presentation/CodeConvention Sample/ViewController.swift
- PopPool/PopPoolTests/PopPoolTests.swift
- 네트워크 기본 통신 데이터 구성
- Clean Architecture 방식에 맞춰 구조 구성 시도
- 네트워크 테스트 작성 -> 일단 제외
- PopPool/Network 디렉토리에 Network 컴포넌트별 추가
e.g) Common, DTO, Endpoint, MockTest, Provider
- PopPoolTests 디렉토리에 testFetchJoke 테스트 메서드 추가
테스트 케이스는 추후 업데이트하기로 진행
> 네트워크 Layer 구성

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- PopPool/PopPool.xcodeproj/xcshareddata/xcschemes/PopPool.xcscheme
- PopPool/PopPool/Application/SceneDelegate.swift
- PopPool/PopPool/Presentation/CodeConvention Sample/ViewController.swift
- PopPool/PopPool/Presentation/Coordinator/AppCoordinator.swift
- PopPool/PopPool/Presentation/Coordinator/ChildrenCoordinator.swift
- PopPool/PopPool/Presentation/Coordinator/Coordinator Test/TestVC.swift
- PopPool/PopPool/Presentation/Coordinator/Coordinator.swift
- Coordinator 패턴 적용 했습니다
- 화면 이동을 볼 수 있도록 버튼을 추가했습니다. 탭해보세요!
- Coordinator Pattern 적용
- App > Main > Base 구조로 Coordinator 구성
- 앱 최초 진입은 AppCoordinator -> MainCoordinator
- 이후 모든 화면 전환은 BaseCoordinator를 적용합니다
> [MERGE]: ✅ Coordinator Pattern 적용, 테스트 화면 추가

- PopPool/PopPool/Domain/Interfaces/LocalDBUseCase.swift
- PopPool/PopPool/Domain/UseCase/LocalDeleteUseCaseImpl.swift
- PopPool/PopPool/Domain/UseCase/LocalFetchUseCaseImpl.swift
- PopPool/PopPool/Domain/UseCase/LocalSaveUseCaseImpl.swift
- PopPool/PopPool/Presentation/Common/Utility/Constants.swift
개발에 사용할 padding 값을 enum으로 생성했습니다
개발단에서 spacing 값을 입력하지 않아도 됩니다
```
enum SpaceGuide {
static let _4px = 4
static let _8px = 8
static let _12px = 12
static let _16px = 16
static let _20px = 20
static let _24px = 24
static let _28px = 28
static let _32px = 32
static let _36px = 36
static let _40px = 40
static let _48px = 48
static let _64px = 64
static let _80px = 80
static let _120px = 120
static let _156px = 156
}
```
> [FEAT]: ✨ Spacing Constant 생성

- PopPool/PopPool/Application/AppDelegate.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
- PopPool/PopPool/Infrastructure/Network/Provider/Provider.swift
- PopPool/PopPool/Infrastructure/Service/AuthService/Services/KakaoAuthServiceImpl.swift
- PopPool/PopPool/Presentation/Common/Enums/SocialTYPE.swift
- tryLogin 수정
- backend의 API를 사용하는데 있어 3가지 이슈가 있어 기록으로 남깁니다.
- FetchUserCredentialUsecase -> AuthUseCase.tryLogin  순서로 실 기기에서 테스트를 진행하였으나 Server is not connected 라는 에러를 콘솔에서 확인함.
- baseURL 수정, Path 수정, Parameter Header, body 변경, Request Body에 들어갈 객체 수정
- Server is not connected 에서 개선이 되지 않음.
- 아! 로컬 서버를 띄워놓고 작업을하는데 모바일 기기에서 요청을하니 서버가 연결이 되지 않는 것은 당연하구나! <br/>바디 파라미터 테스트 객체 구현 후 - 시뮬레이터로 실행
- Issue2로 넘어감..
- 앞서 우당탕탕 아무거나 시도해 보느라 body parameter를 query parameter에 넣어서 실행
- 당연하게도 Bad Request ..
- 다시 정신을 차리고 body parameter에 추가하여 요청을 하였으나 415 에러가 나옴
- 415가 뭐야!! 검색 시작.. 데이터는 오는데 415 지원되지 않는 미디어 유형이라는 것을 확인.!
- setValue 메서드를 이용하여 해결..!
- 우리가 시도하였던 과정들이 합쳐저서 해결할 수 있었던 것 같다..! baseUrl 수정, path 수정, request Data 수정, 실행 환경 변경 등이 합쳐저서 문제를 해결할 수 있었다.!
- Jack: HTTP, CS공부 조금이나마... 해서... 다행이.. 다..
- 서준영: …
> [Trouble Shooting] : 🔥 Network 연결 및 nativekey 변경

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Domain/Interfaces/DeleteLocalUseCase.swift
- PopPool/PopPool/Domain/Interfaces/FetchLocalUseCase.swift
- PopPool/PopPool/Domain/Interfaces/SaveLocalUseCase.swift
- PopPool/PopPool/Domain/UseCase/LocalUseCaseImpl/DeleteLocalUseCaseImpl.swift
- PopPool/PopPool/Domain/UseCase/LocalUseCaseImpl/FetchLocalUseCaseImpl.swift
- PopPool/PopPool/Domain/UseCase/LocalUseCaseImpl/SaveLocalUseCaseImpl.swift
- PopPool/PopPool/Presentation/Common/Cells/UITableViewCell/MenuListCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UITableViewCell/MyCommentCircleListCell.swift
- PopPool/PopPool/Presentation/Common/Interfaces/Cellable.swift
- PopPool/PopPool/Presentation/Common/Interfaces/TableViewSectionable.swift
- PopPool/PopPool/Presentation/Components/ListTitleViewCPNT.swift
- PopPool/PopPool/Presentation/Components/ProfileCircleImageViewCPNT.swift
- PopPool/PopPool/Presentation/Components/TextUnderBarButtonCPNT.swift
- PopPool/PopPool/Presentation/Scene/MyPage/MyPageMainVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Views/MyPageMainProfileView.swift
- TableViewSectionable 을 사용하여 다양한 Cell을 사용하는 TableView를 쉽게 구성 할 수 있습니다.
- ProfileCircleImageViewCPNT 개발
- ListTitleViewCPNT 개발
- TextUnderBarButtonCPNT 개발
```
// 색션을 구성할 샐을 선택하여 Section생성
struct MyCommentCircleListCellSection: TableViewSectionable {
struct Input {
var sectionTitle: String?
}
struct Output {
var didTapRightButton: ControlEvent<Void>
}
typealias CellType = MyCommentCircleListCell
var sectionInput: Input
var sectionCellInputList: [MyCommentCircleListCell.Input]
lazy var titleView: ListTitleViewCPNT = {
let view = ListTitleViewCPNT(title: sectionInput.sectionTitle, size: .medium)
view.titleLabel.font = .KorFont(style: .bold, size: 16)
return view
}()
mutating func makeHeaderView() -> UIView? {
let containerView = UIView()
containerView.backgroundColor = .systemBackground …
```
> [MERGE]: ✅ TableViewSectionable 개발, 컴포넌트 개발

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Data/Repositories/SignUpRepository/SignUpRepositoryTest.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/LargeChipCell.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/SignUpVC.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Views/SignUpStep3View.swift
- PopPool/PopPool/Presentation/Shared/AgeSelectModalVC.swift
- PopPool/PopPool/Presentation/Shared/InterestSelectedView.swift
- 관심사 선택 컬렉션뷰 모듈화
- InterestSelectedView의 selectedList, categoryList를 사용하시면 됩니다.
- categoryList를 accept를 이용하여 리스트를 설정하면 reload를 진행합니다.
- 5개 이상 리스트를 선택시 Toast MSG를 띄웁니다.
- 성별 선택, 나이 선택 뷰는 모듈화를 하는 것이 무의미하다 판단하여 진행하지 않았습니다.
> [FEAT] : ⚙️ 관심사 선택 컬렉션뷰 모듈화

- PopPool/PopPool/Data/Network/PopPoolNetwork/LoginDTO/LoginResponseDTO.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/Auth/LoginResponse.swift
- API수정사항 반영
- LoginResponseDTO 수정
> [MERGE] : ✅ LoginResponse DTO FIX

- PopPool/PopPool/Presentation/Components/ListContentCPNT.swift
- PopPool/PopPool/Presentation/Scene/Home/HomeAlertVC.swift
- 병합 이후 발생하는 프로젝트 빌드 이슈를 해결했습니다.
- BaseViewController 적용
- ListContentCPNT의 setUp 메서드 접근 제어 변경
> [HotFix]: 💥🚚 project 빌드 오류 수정

- PopPool/PopPool/Data/Repositories/MapRepository/FilterRepository.swift
- PopPool/PopPool/Domain/Interfaces/FilterUseCase.swift
- PopPool/PopPool/Presentation/Scene/Map/PopUpListView/FilterBottomSheetViewModel.swift
- 빌드가 되지 않던 이슈를 해결하였습니다.
- Filter 관련 파일 주석 처리
- FilterRepository, FilterUsecase, FilterBottomSheetViewModel
> [HotFix]: 💥🚚 FilterUsecase 및 implementation 주석 처리

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/UpdateRequestDTO/UpdateMyInterestRequestDTO.swift
- PopPool/PopPool/Data/Repositories/UserRepository/UserRepositoryImpl.swift
- PopPool/PopPool/Domain/Interfaces/UserRepository.swift
- PopPool/PopPool/Infrastructure/Service/KeyChainService/KeyChainServiceImpl.swift
- PopPool/PopPool/Presentation/Components/HeaderViewCPNT.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/Category/ProfileEditCategoryBottomSheetVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/Category/ProfileEditCategoryBottomSheetVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/User/ProfileEditUserDataBottomSheetVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/User/ProfileEditUserDataBottomSheetVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/ProfileEditVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/ProfileEditVM.swift
- PopPool/PopPool/Presentation/Shared/InterestSelectedView.swift
- 프로필 카테고리 수정 API 연결
- 프로필 유저 정보 수정 API 연결
- 카테고리 수정 부분 추가는 확인 하였으나 삭제 부분이 적용이 되지 않아 백엔드 분에게 확인 요청한 상황입니다. API 수정이 완료되면 수정없이 정삭 작동 할 것으로 예상 중입니다.
https://github.com/user-attachments/assets/9fff6824-3f19-4532-ba94-8bdfba7888e4
> [MERGE]: ✅ 프로필 수정 페이지 기능 연결 (프로필 이미지 제외)

- PopPool/PopPool.xcodeproj/project.pbxproj
- 머지 이후 폴더링되지 않았던 파일의 폴더 reference 위치를 변경하였습니다.
- 폴더링 구조를 변경하기 이전 작업하던 파일이었던만큼, 폴더링으로 인해 이루어질 hotfix는 이번 PR 이외에 한 번 정도 더 있을 수 있을 것 같습니다. 참고만 부탁 드립니다!
> [HOTFIX] 💥🚚 : InquiryVC 파일 reference 수정

- PopPool/PopPool/Data/Network/PopPoolNetwork/LoginDTO/LoginResponseDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/GetMyPageResponseDTO.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/Auth/LoginResponse.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/GetMyPageResponse.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVM.swift
- 다들 로그인이 급하실 것 같아서 브랜치 하나 만들어서 PR올립니다.!
- LoginResponse DTO, Entitie Fix
- GetMyPageResponse DTO, Entitie Fix
> [MERGE]: Login DTO Fix

- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/SavedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/ViewedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Extension/String+.swift
- PopPool/PopPool/Presentation/Scene/MyPage/FavoritePopUp/FavoritePopUpVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/FavoritePopUp/FavoritePopUpVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/RecentPopUp/RecentPopUpVC.swift
-  찜한 팝업 API연결
-  DateFormatter 수정
https://github.com/user-attachments/assets/6d60cc41-866a-463b-936b-3c10a5ae4608
> [MERGE]: 찜한 팝업 API연결 Date Convert 수정

- PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/InfoDTO/BlockedUserInfoDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/UserUnblockRequestDTO.swift
- PopPool/PopPool/Data/Repositories/UserRepository/UserRepositoryImpl.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/BlockedUserInfo.swift
- PopPool/PopPool/Presentation/Components/ListInfoButtonCPNT.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Blocked/BlockedUserCell.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Blocked/BlockedUserVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Blocked/BlockedUserVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- 차단한 사용자 기능 연결
https://github.com/user-attachments/assets/9767acce-72c9-4632-9023-ff2600270d43
> [MERGE]: 차단한 사용자 기능 연결

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
- PopPool/PopPool/Presentation/Common/Cells/TableViewSection/MenuListCellSection.swift
- PopPool/PopPool/Presentation/Common/Cells/UITableViewCell/MenuListCell.swift
- PopPool/PopPool/Presentation/Common/Interfaces/TableViewSectionable.swift
- PopPool/PopPool/Presentation/Scene/MyPage/FavoritePopUp/FavoritePopUpVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/FavoritePopUp/FavoritePopUpVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/Views/MyPageMainProfileView.swift
- Favorite popup pagination적용
- profile이미지 기본 이미지 설정
- 버전 정보 표시
https://github.com/user-attachments/assets/33eeca4b-995f-4dfd-b93c-df9a5c32ce96
> [MERGE]: Favorite popup pagination적용 및 profile이미지 기본 이미지 설정, 버전 정보 표시

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/SignOut/SignOutSurveyView.swift
- PopPool/PopPool/Presentation/Scene/MyPage/SignOut/SignOutVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/SignOut/SignOutVM.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/SignUp/Components/TermsViewCPNT.swift
- SignOutVC의 기능을 수정하였습니다.
- SignOutVM에 서베이 데이터를 호출해오는 메서드를 추가하였습니다.
- dynamic Textfield가 스크롤 되지 않던 이슈 해결
- 서베이 API 호출 이후 데이터가 화면에 보여지도록 구성 수정
- 탭한 서베이 값을 알려주는 publishRelay 프로퍼티 추가
- 서베이 내용이 길어짐에 따라 view의 높이보다 커질 경우 scroll 기능 활성화
https://github.com/user-attachments/assets/b55bb2da-4f60-43b4-ad87-5e1529208ad5
> [MERGE]: ✅ SignOutVc 기능 수정 및 API 데이터 연결

- PopPool/PopPool/Presentation/Scene/MyPage/Blocked/BlockedUserVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/FavoritePopUp/FavoritePopUpVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/MyCommentedPopUp/MyCommentedPopUpVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/RecentPopUp/RecentPopUpVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/RecentPopUp/RecentPopUpVM.swift
- 최근 본 팝업 Pagination 적용
- 다른 pagination적용 화면 size 20으로 변경
https://github.com/user-attachments/assets/7d5905a3-7ab1-4b93-828c-ccb04e402778
> [MERGE]: 최근 본 팝업 Pagination 적용

- PopPool/PopPool/Presentation/Scene/Home/AlarmSettingVC.swift
- PopPool/PopPool/Presentation/Scene/Home/AlarmSettingVM.swift
- 앱 푸시 버튼 탭 시 설정 페이지 알림 상태를 검토하여 설정 페이지로 사용자를 보낼지 말지 확인합니다
- 알람 설정 이후 사용자가 별도로 설정 페이지에서 알람을 끌 경우, 서비스 알림이 꺼지도록 정리하였습니다.
> [MERGE]: ✅ 알림 설정 페이지 일부 수정 머지

- PopPool/PopPool/Presentation/Scene/Home/AlarmSettingVC.swift
- PopPool/PopPool/Presentation/Scene/Home/AlarmSettingVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/LoggedHomeVC.swift
- LoggedHomeVC 헤더 이미지 업데이트 적용
- delegate 패턴을 통해 activity Toggle을 안내
> [MERGE]: ✅ activity Alert 토글에 따른 UI 업데이트

- PopPool/PopPool/Presentation/Components/LoadingIndicator.swift
- 인디케이터 플레이 속도 변경
- 인디케이터 플레이 속도가 1.0 > 1.5로 변경되었습니다.
> [MERGE] : ✅ indicator 속도 조절

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Data/Network/PopPoolNetwork/AdminDTO/AdminPopUpStoreIdRequestDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/AdminDTO/GetAdminPopUpStoreDetailResponseDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/AdminDTO/UpdatePopUpStoreRequestDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/PopPoolAPIEndPoint.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/GetMyPageResponseDTO.swift
- PopPool/PopPool/Data/Repositories/AdminRepository/AdminRepositoryImpl.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/GetMyPageResponse.swift
- PopPool/PopPool/Presentation/Scene/Admin/Edit/AdminEditVC.swift
- PopPool/PopPool/Presentation/Scene/Admin/Management/AdminManagementVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/Category/ProfileEditCategoryBottomSheetVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/BottomSheet/Category/ProfileEditCategoryBottomSheetVM.swift
> [MERGE]: QA일부 반영 및 admin 페이지 삭제기능 추가

- PopPool/PopPool/Application/SceneDelegate.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/GetMyPageResponseDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/GetProfileResponseDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/UpdateRequestDTO/UpdateMyProfileRequestDTO.swift
- PopPool/PopPool/Data/Repositories/UserRepository/UserRepositoryImpl.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/GetMyPageResponse.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/GetProfileResponse.swift
- PopPool/PopPool/Domain/Interfaces/UserRepository.swift
- PopPool/PopPool/Domain/Interfaces/UserUseCase.swift
- PopPool/PopPool/Domain/UseCase/UserUseCaseImpl.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/Views/MyPageMainProfileView.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/ProfileEditVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/ProfileEdit/ProfileEditVM.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVC.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVM.swift
-  마이페이지 이미지 업로드, 수정 기능 추가, 알림설정 삭제, 로그인 분기 삭제
https://github.com/user-attachments/assets/55669a76-18db-4da4-b000-978773d2e403
> [MERGE]: 마이페이지 이미지 업로드, 수정 기능 추가, 알림설정 삭제, 로그인 분기 삭제

- PopPool/PopPool/Data/Network/PopPoolNetwork/UserDTO/InfoDTO/PopUpInfoDTO.swift
- PopPool/PopPool/Domain/Entities/NetworkResponse/User/PopUpInfo.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/SavedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/ViewedPopUpCell.swift
- 찜한 팝업, 최근 본 팝업 PresignedURL 적용
> [MERGE]: 찜한 팝업, 최근 본 팝업 PresignedURL 적용

- PopPool/PopPool/Data/Network/PopPoolNetwork/AdminDTO/CreatePopUpStoreRequestDTO.swift
- PopPool/PopPool/Presentation/Scene/Admin/Edit/AdminEditVC.swift
- PopPool/PopPool/Presentation/Scene/Admin/Management/AdminManagementListTableViewCell.swift
- PopPool/PopPool/Presentation/Scene/Admin/Post/AdminPostVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/MyPageMainVM.swift
> [MERGE]: Admin 기능 구현

- PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- PopPool/PopPool/Presentation/Common/Manager/ClipboardManager.swift
- 인스타그램 콘텐츠 링크 복사시 발생하는 추가 콘텐츠 내용 강제 누락
> [MERGE]: ✅ IG Link 인식 이슈 해결

- PopPool/PopPool/Data/Network/PopPoolAPIEndPoint.swift
- replaced extraneous '}' within Endpoint
> [Hotfix]: 🚚💥 endpoint 컴파일 오류 수정

- PopPool/PopPool/Presentation/Common/Extension/UIView+.swift
- PopPool/PopPool/Presentation/Components/ToolTipViewCPNT.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/DismissCommentModalVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/InstagramCommentView/SocialCommentVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/NormalCommentVC.swift
- 툴팁의 중앙 정렬 이슈를 해결하였습니다
- 길이에 상관없이 툴팁이 잘 나옵니다
- 소셜 코멘트VC에서 화면 이탈 분기를 정리하였습니다.
> [MERGE]: ✅ 소셜 코멘트, 툴팁 컴포넌트 수정

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool/Data/Network/PopPoolAPIEndPoint.swift
- PopPool/PopPool/Data/Repositories/LikeRepository/LikeRepositoryImpl.swift
- PopPool/PopPool/Domain/Interfaces/LikeRepository.swift
- PopPool/PopPool/Domain/Interfaces/LikeUseCase.swift
- PopPool/PopPool/Domain/UseCase/LikeUseCaseImpl.swift
- PopPool/PopPool/Presentation/Common/Extension/UIView+.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/EntirePopupVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/EntirePopupVM.swift
- Like API 호출할 수 있도록 repository를 정리하였습니다.
- 호출에 문제가 생긴다면 말씀 부탁 드립니다!
- 북마크 버튼 탭 시 계속해서 API 호출이 되고 있는 상황이 불필요해보여서 해당 뷰컨트롤러에서 나갈 때 호출이 될 수 있도록 정리하였습니다.
*다른 브랜치에 작업한 줄 알았는데, 같이 올라갔네요... 😢
> [MERGE]: ✅ Like API repository 정리

- PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/ImageActionDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/PostCommentRequestDTO.swift
- PopPool/PopPool/Data/Network/PopPoolNetwork/CommentDTO/UpdateCommentRequestDTO.swift
- PopPool/PopPool/Data/Repositories/CommentRepository/CommentRepositoryImpl.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/CommentTypeVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/InstagramCommentView/SocialCommentVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/InstagramCommentView/SocialCommentVM.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/NormalCommentVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/DetailComment/NormalCommentVM.swift
- PopPool/PopPool/Presentation/Scene/PopUpDetail/PopUpDetailViewController.swift
- 댓글을 업로드할 수 있습니다
*인스타그램 댓글 업로드 시 최초에 간혹 이미지를 가져오지 못하는 이슈가 있습니다.. 이슈 파악 중
- 노말 댓글 작성 시, popupId를 통해 발송하고 있지 않아 문제가 발생하고 있었습니다
- 댓글들이 각각 폴더에 잘 들어가는 것을 확인하였습니다.
> [MERGE]: ✅ 코멘트 작성 서버 업로드 연결 이슈 해결

- PopPool/PopPool.xcodeproj/project.pbxproj
- PopPool/PopPool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/PopularViewCell.swift
- HomeVC의 셀 UI를 변경하였습니다.
- 중복 데이터를 확인하는 snapShot의 이슈를 해결하였습니다.
> [MERGE]: ✅ snapShot, homeViewCell UI 수정, date 재확인 필요

- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/CircleFeedCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/SavedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/ViewedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Extension/UIImageView+.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeCollectionViewCell.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/HomeVC.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/PopularViewCell.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Main/Views/MyPageMainProfileView.swift
- PopPool/PopPool/Presentation/Scene/MyPage/MyCommentedPopUp/Cells/PopUpCommentedCell.swift
- 이미지 인디케이터 적용
- presignedUrl로 이미지 처리
> [MERGE]: ✅ presignedUrl 이미지 연결, loading indicator 적용

- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/SavedPopUpCell.swift
- PopPool/PopPool/Presentation/Common/Cells/UICollectionViewCell/ViewedPopUpCell.swift
- PopPool/PopPool/Presentation/Scene/MyPage/Home/PopularViewCell.swift
- PopPool/PopPool/Presentation/Scene/OnBoarding/Login/LoginVM.swift
- Seg 2와 3 일부에서 이미지 데이터 출력 이슈를 해결하였습니다 (presignedUrl에서 잘 받아 오고 있습니다.)
- homeVC에서 출력되고 있던 날짜 데이터 또한 '~월 ~일' 순으로 처리되도록 정리하였습니다.
- login 당시 취소 버튼 탭 시, 별도 오류 메시지 없이 내려갈 수 있도록 처리하였습니다.
> [MERGE]: ✅ UI 및 메시지 내용 수정 > SocialLogin Error
